### ISSUE TITLE
Umbrella issue for editor simplification

### ISSUE THREAD

**Issue by miyconst** [Juicy/juicy-tile-editor#97]
On today's meeting with @Starcounter-Jack, @tomalec, @warpech, and me were decided:
- [ ] 1. Applications should put tiles into logical groups within an html tag.
- [ ] 2. Applications should provide default setup for individual elements which would look good in the groups.
- [ ] 3. Editor should be able to unwrap such groups.
- [x] 4. [Editor should have two (three in the future) modes: standard and advanced.](https://github.com/Juicy/juicy-tile-editor/issues/98)
- [x] 5. The standard mode should display only a few controls: [media-screen selection, width buttons, priority buttons, visible eye-button].
- [x] 6. [The standard mode tree shows only root elements.](https://github.com/Juicy/juicy-tile-editor/issues/99)
- [x] 7. In the advance mode all of the controls are available.
- [ ] 8. Editor should automatically recognize label-control pairs if label contains `id` attribute and there is a control with such `id`. [Patterns](https://github.com/Starcounter/RebelsLounge/issues/14).
- [ ] 9. Launcher should be able to provide design patterns for label-control pairs.

@tomalec which points do you think is better to start from? I will convert them into issues and start implementing.

**Comment by tomalec** [comment]
@Starcounter-Jack, @warpech, @miyconst Correct me if I'm wrong, but 
- Regarding 1. I think we agreed that we do not limit ourselves to `<fieldset>` but editor/grid would be able to explode any element,
-  Ad. 5. media-screen selection -> element/partial query range  selections,
-  Ad. 6. I thought it was about just root/top-level elements, not only groups,
- Ad. 8. The patters are listed here https://github.com/Starcounter/RebelsLounge/issues/14,
- Ad. 9. not only for pairs, the Layout would be for entire group of elements.

**Comment by tomalec** [comment]
I would say, It's good to start with 4,5,7 as it does not require any change in engine, just re-arranging controlls

**Comment by miyconst** [comment]
@tomalec I have updated the issue text with your notes, but I don't fully understand these:

> 1. media-screen selection -> element/partial query range selections.
> 2. not only for pairs, the Layout would be for entire group of elements.

**Comment by miyconst** [comment]
Update check list state.

**Comment by miyconst** [comment]
Closing the issue as too old. The left features are tracked in separated issues.

**Comment by tomalec** [comment]
Moreover new simplification plan popped out https://github.com/Starcounter/RebelsLounge/issues/32
